# Generated by Django 5.2.4 on 2025-07-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(default='General Medicine', max_length=100),
        ),
        migrations.AlterField(
            model_name='nurseprofile',
            name='department',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='nurseprofile',
            name='shift',
            field=models.CharField(default='Day', max_length=20),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
